### PR TITLE
Regression test: Add ML tests to set of regression test

### PR DESCRIPTION
**Pull request by emacdo12**
#### Description

Benchmarks that test machine learning. Includes: generate blocks with for,ifs and case statements. Input.output files declared withing a module.$clog function. paramter overrides and defparam. Initial statements. Always blocks.

#### Motivation and Context

Additional feature.

#### How Has This Been Tested?

Ran make test, passed all tests.

#### Types of changes

- [ ] Bug fix (change which fixes an issue)
- [x] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by jeanlego** [comment]
`Benchmarks that test machine learning` this isnt machine learning, this would be part of keyword support, (bugs reported from the ML benchmarks)

**Comment by emacdo12** [comment]
I was told the ML stood for machine learning but that makes more sense

**Comment by jeanlego** [comment]
>I was told the ML stood for machine learning but that makes more sense

yeah no these are broken keyword and syntax features that prevents us from running the ML benchamrks (which we dont have yet)

**Comment by emacdo12** [comment]
Okay I see when I do the PR for the main repo I'll edit the description

**Comment by jeanlego** [comment]
> Okay I see when I do the PR for the main repo I'll edit the description

also move the test to the relevant directory

**Comment by jeanlego** [comment]
this will be merged in syntax and keyword so i will close

**Pull request closed without merging**
