### PR TITLE
Odin: Improved documentation

### PR DESCRIPTION
**Pull request by emacdo12**
#### Description

Added segment about useful tools for developpers and also a brief summary of Odin steps. (Build ast->elaborate->netlist).

#### Types of changes

- [ ] Bug fix (change which fixes an issue)
- [x] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [ ] My change requires a change to the documentation
- [x] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by emacdo12** [comment]
blif
ast
These are the two graphs in the new documentation

**Comment by jeanlego** [comment]
I don't see any issue other than the graph, the build netlist part is a bit vague and output blif can happen at any phase of the netlist

**Comment by jeanlego** [comment]
@emacdo12 ping

**Comment by jeanlego** [comment]
moved on main repo, closing

**Pull request closed without merging**
